name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env.local

      - name: Run Cypress tests headlessly
        run: npm run e2e:headless
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Archive videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos
